apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-dep
  labels:
    app: user-service-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service-api
  template:
    metadata:
      labels:
        app: user-service-api
    spec:
      containers:
        - image: javasre2022/userservice
          imagePullPolicy: Always
          name: user-service-api
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: userservice-service
spec:
  selector:
    app: user-service-api
  ports:
    - port: 8085
      targetPort: 8085
